### PR TITLE
Readiness gates implementation for eager mode

### PR DESCRIPTION
**Pull request by uthark**
Fix for #126.
This is work in progress

### CODE REVIEW

**Comment by uthark** [comment]
@eytan-avisror what is the best place to check readiness gates for lazy mode? 
right now `isNodeReady` check doesn't work in lazy mode too.

**Comment by uthark** [comment]
Tested eager mode and confirmed feature works as expected.

**Review by eytan-avisror — APPROVED** [review]
Looks good to me 👍 
Will give some time before merging in case @shrinandj has any comments

**Review by shrinandj — APPROVED** [review]
This looks great. Thanks for implementing it @uthark !

**Pull request merged**
