### PR TITLE
using TerminateInstanceInAutoScalingGroup instead of TerminateInstances

### PR DESCRIPTION
**Pull request by deepakbenny**
resolves issue #18 

 * Updates for using TerminateInstanceInAutoScalingGroup
 * removed imports of ec2iface and ec2
 * Updated tests to use autoscaling interface.

### CODE REVIEW

**Comment by shrinandj** [comment]
The build failed with the following errors:

```
# github.com/keikoproj/upgrade-manager/controllers
--
  | controllers/rollingupgrade_controller.go:213:115: undefined: autoscalingiface.AutoscalingAPI
  | controllers/rollingupgrade_controller.go:215:12: undefined: autoscaling.TerminateInstanceInAutoscalingGroupInput
  | controllers/rollingupgrade_controller.go:349:115: undefined: autoscalingiface.AutoscalingAPI
  | controllers/rollingupgrade_controller.go:622:117: undefined: autoscalingiface.AutoscalingAPI
  | controllers/rollingupgrade_controller.go:693:196: undefined: autoscalingiface.AutoscalingAPI
  | # github.com/keikoproj/upgrade-manager/controllers [github.com/keikoproj/upgrade-manager/controllers.test]
  | controllers/rollingupgrade_controller.go:213:115: undefined: autoscalingiface.AutoscalingAPI
  | controllers/rollingupgrade_controller.go:215:12: undefined: autoscaling.TerminateInstanceInAutoscalingGroupInput
  | controllers/rollingupgrade_controller.go:349:115: undefined: autoscalingiface.AutoscalingAPI
  | controllers/rollingupgrade_controller.go:622:117: undefined: autoscalingiface.AutoscalingAPI
  | controllers/rollingupgrade_controller.go:693:196: undefined: autoscalingiface.AutoscalingAPI
  | make: *** [Makefile:42: vet] Error 2
```
https://keikoproj-upgrade-manager.semaphoreci.com/jobs/18fc9eb1-8f2e-412f-ac56-668871061318

**Comment by deepakbenny** [comment]
Not able to view https://keikoproj-upgrade-manager.semaphoreci.com/jobs/18fc9eb1-8f2e-412f-ac56-668871061318, returning a 404.

Will check if i can set this up locally.

**Comment by deepakbenny** [comment]
@shrinandj can you please share the logs from the build. My local build is working fine.

**Comment by kianjones4** [comment]
@deepakbenny logs: 
> 2019/10/02 10:00:53 foo: Waiting for postDrainDelay
>   | --- FAIL: TestDrainNodePostDrainFailureToDrain (0.00s)
>   | rollingupgrade_controller_test.go:285:
>   | Expected
>   | <nil>: nil
>   | not to be nil
>   | --- FAIL: TestTerminateNodeSuccess (0.00s)
>   | panic: runtime error: invalid memory address or nil pointer dereference [recovered]
>   | panic: runtime error: invalid memory address or nil pointer dereference
>   | [signal SIGSEGV: segmentation violation code=0x1 addr=0x578 pc=0x13ff0a2]
>   |  
>   | goroutine 374 [running]:
>   | testing.tRunner.func1(0xc0000ed800)
>   | /usr/local/go/src/testing/testing.go:830 +0x392
>   | panic(0x15753a0, 0x2793240)
>   | /usr/local/go/src/runtime/panic.go:522 +0x1b5
>   | github.com/keikoproj/upgrade-manager/controllers.(*MockAutoscalingGroup).TerminateInstanceInAutoScalingGroup(0xc000550bd0, 0xc000552bc0, 0x7f54c5e1fe10, 0xc000423be0, 0x40d829)
>   | <autogenerated>:1 +0x32
>   | github.com/keikoproj/upgrade-manager/controllers.(*RollingUpgradeReconciler).TerminateNode(0xc000423ce0, 0xc0003afd78, 0x172f44d, 0xc, 0x1a730a0, 0xc000550bd0, 0x203000, 0x19)
>   | /root/upgrade-manager-v1/controllers/rollingupgrade_controller.go:220 +0xee
>   | github.com/keikoproj/upgrade-manager/controllers.TestTerminateNodeSuccess(0xc0000ed800)
>   | /root/upgrade-manager-v1/controllers/rollingupgrade_controller_test.go:315 +0x1e5
>   | testing.tRunner(0xc0000ed800, 0x17c8180)
>   | /usr/local/go/src/testing/testing.go:865 +0xc0
>   | created by testing.(*T).Run
>   | /usr/local/go/src/testing/testing.go:916 +0x35a
>   | FAIL	github.com/keikoproj/upgrade-manager/controllers	3.995s
>   | make: *** [Makefile:13: test] Error 1
>   | exit code: 2 duration: 120s

can you install [kubebuilder](https://book-v1.book.kubebuilder.io/getting_started/installation_and_setup.html) and try running `make test`? That way you can see where your build is failing.

**Comment by deepakbenny** [comment]
@kianjones4 @shrinandj can you please review?

**Comment by shrinandj** [comment]
Thanks for your contributions @deepakbenny !

**Pull request merged**
